# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: BonnPatch Tutorial
author: Manuel Hinz
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - ion.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/mathmanuelhinz/bonnpatch  
  branch: main

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

only_build_toc_files: true
